/// <auto-generated>
/// The file was generated by GenOne (v1.0.0.4)
/// Learn more at https://github.com/mrlacey/GenOne
/// </auto-generated>

namespace CSharpExample;

enum UserType
{
    Attendee,
    Helper,
    Organiser,
    Sponsor,
}
partial class User : Person
{
    public User(string Name, string Age) {
        Name = Name;
        Age = Age;
    }
    public string Name { get; }
    public string Age { get; }
}
partial class Earth
{
    public string DeepSeas { get; set; }
    public BodyOfWater Seas { get; set; }
}
partial class Sea
{
    public string Depth { get; set; }
    public float NauticalDepth { get; set; }
    public IEnumerable<Fish> Fishes { get; set; }
}
partial class Mountain
{
    public string Altitude { get; set; }
}
partial class Sun
{
    public partial void Shine() { }
}
partial class Expanse
{
    public partial void Separate(Waters Waters) { }
}

