/// <auto-generated>
/// The file was generated by GenOne (v0.1.1.6)
/// </auto-generated>

namespace CSharpExample;

enum UserType
{
    Attendee,
    Helper,
    Organiser,
    Sponsor,
}
partial class User : Person
{
    public string Name { get; init; }
}
partial class Earth
{
    public string DeepSeas { get; set; }
    public BodyOfWater Seas { get; set; }
}
partial class Sea
{
    public string Depth { get; set; }
    public float NauticalDepth { get; set; }
    public IEnumerable<Fish> Fishes { get; set; }
}
partial class Mountain
{
    public string Altitude { get; set; }
}
partial class Sun
{
    public partial void Shine() { }
}
partial class Expanse
{
    public partial void Separate(Waters Waters) { }
}

