/// <auto-generated>
/// The file was generated by GenOne (v1.0.0.4)
/// Learn more at https://github.com/mrlacey/GenOne
/// </auto-generated>

namespace CSharpExample;

partial class user
{
    public user(string name) {
        name = name;
    }
    public string name { get; }
    public string emailAddress { get; set; }
    public partial void Authenticate() { }
}

