/// <auto-generated>
/// The file was generated by GenOne (v1.0.0.4)
/// Learn more at https://github.com/mrlacey/GenOne
/// </auto-generated>

namespace CSharpExample;

partial class light
{
    public light(string brightness) {
        brightness = brightness;
    }
    public string brightness { get; }
    public partial void Shine() { }
}

