/// <auto-generated>
/// The file was generated by GenOne (v1.0.0.4)
/// Learn more at https://github.com/mrlacey/GenOne
/// </auto-generated>

namespace CSharpExample;

enum Gender
{
    Male,
    female,
}
partial class light
{
    public light(string brightness) {
        brightness = brightness;
    }
    public string brightness { get; }
    public partial void Shine() { }
}
partial class Person
{
    public Gender Sex { get; set; }
}
partial class sky
{
    public IEnumerable<Light> lights { get; set; }
}
partial class Expanse
{
    public partial void Separate(waters waters) { }
}

