using System.Linq;
using System.Text;
using GenOne.Logic;
using Microsoft.VisualStudio.TextTemplating.VSHost;

namespace GenOne.Generators
{
    public class GenOnePythonGenerator : BaseCodeGeneratorWithSite
    {
        public const string Name = nameof(GenOnePythonGenerator);

        public const string Description = "Create Python classes from .gen1 docs";

        public override string GetDefaultExtension() => ".py";

        protected override byte[] GenerateCode(string inputFileName, string inputFileContent)
        {
            var lines = inputFileContent.Split(new[] { Environment.NewLine }, StringSplitOptions.None);

            var tLines = Tokenizer.TokenizeLines(lines.ToList());
            var cLines = Classifier.ClassifyLines(tLines);

            var generated = PythonGenerator.GenerateOutput(cLines);

            var sb = new StringBuilder();

            ////sb.AppendLine("/// <auto-generated>");
            ////sb.AppendLine($"/// The file was generated by GenOne (v{Vsix.Version})");
            ////sb.AppendLine($"/// Learn more at https://github.com/mrlacey/GenOne");
            ////sb.AppendLine("/// </auto-generated>");
            ////sb.AppendLine();
            ////sb.AppendLine($"namespace {FileNamespace};");
            ////sb.AppendLine();
            sb.AppendLine($"{generated}");

            return Encoding.UTF8.GetBytes(sb.ToString());
        }
    }
}
