// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenOne
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommandVisisiblityString = "e0dbe5b2-5943-4376-8c31-54b314dcfa27";
        public static Guid CommandVisisiblity = new Guid(CommandVisisiblityString);

        public const string GenOneCsGeneratorString = "04d489b2-e54c-4245-9b5c-fa2aa222f4d8";
        public static Guid GenOneCsGenerator = new Guid(GenOneCsGeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}